### ISSUE TITLE
failed to boot - telnet

### ISSUE THREAD

**Issue by piotrekcrash** [ubports-santoni/projectmanagement#19]
Hi,
I installed on my device (Xiaomi 4X 3/32GB) by steps:
 - unlock bootloader
 - write twrp over fastboot
 - write halium-boot.img (from Actions section - last available)
 - write system and rootfs: halium-install -p ut rootfs.tar.gz system.img

But the system not up. Device recognized as "failed to boot". So I connected via telnet and read dmsg log and some other. Can you check what is wrong? Probably I skipped something or not fully understand. 

[dmesgtail.log](https://github.com/ubports-santoni/projectmanagement/files/4169871/dmesgtail.log)
[ls.log](https://github.com/ubports-santoni/projectmanagement/files/4169872/ls.log)
[dfh.log](https://github.com/ubports-santoni/projectmanagement/files/4169873/dfh.log)
[dmesg.log](https://github.com/ubports-santoni/projectmanagement/files/4169874/dmesg.log)

**Comment by Danct12** [comment]
You are using F2FS, this is not supported by UBports and even us, please switch to ext4.

This can be done by go to TWRP, **THIS WILL REMOVE ALL YOUR DATA!**
Wipe -> Advanced wipe -> select the data partition -> change file system -> ext4.

Then after that you can run halium-install again.

**Comment by piotrekcrash** [comment]
@Danct12 I already did that before opening an issue. TWRP shows there:
Mount Point: /data
File system: ext4
Present: Yes

Is this possible TWRP wrongly recognize that? TWRP version 3.3.1-0.
I tried one more time to change the file system to ext4 but the result is the same - TWRP show ext4 but in logs still same errors.

**Comment by Danct12** [comment]
Can you give the output of "mount" in TWRP shell?

Anyway, last thing you can try is to go to Wipe and "Format Data" and try flash again.

**Comment by piotrekcrash** [comment]
@Danct12 when I changed data fs to ext4 and then install it not worked but when I do it and later change one more time to ext4 and install again it Works! Many Thanks;)
