### ISSUE TITLE
[SYS] No sound on ARM64

### ISSUE THREAD

**Issue by tjitra** [ubports-santoni/projectmanagement#25]
**Describe the bug**
 no sound from ringtone, touch, music
 sound from call good and work

**Device Information:**
 - Device: Redmi 4X
 - Kernel: last Ci build
 - Rootfs: ARM64
 - Are you using Anbox?: No

**Additional context**
  flash from debian buster multi architecture
  reflash with non rotfs 64 its run so smooth

**Comment by Danct12** [comment]
Fixed in https://github.com/ubports-santoni/android_device_xiaomi_santoni/commit/821c080422d2e3ceedfbf5a90c2b628cc592afda and https://github.com/ubports-santoni/android_device_xiaomi_santoni/commit/941515d2c25daed71e4c7919df6b07c481a8f273
