### ISSUE TITLE
Kernel Module support for TP-Link TL-WN722N

### ISSUE THREAD

**Issue by shafr** [ubports-santoni/projectmanagement#27]
**Describe the bug**
I love ability to install almost any linux app on phone. I think it would be a great penetration testing device in a pocket.
However support for Wifi cards was removed (probably to save space).
Removal comment: https://askubuntu.com/questions/823831/ubuntu-touch-usb-wifi-dongle

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:**
 - Device: Redmi 4X 
 - Kernel: 3.18.140-ubports]
 - Rootfs: ARM64
 - Are you using Anbox?: Not sure
 - If kernel panic, please attach the output of /proc/last_kmsg as an attachment.

**Additional context**
You can find info on building at https://itectec.com/ubuntu/ubuntu-how-to-install-driver-for-tp-link-tl-wn722n-on-ubuntu-14-04/

Where can I find kernel sources ?

**Comment by Danct12** [comment]
I don't have this Wi-Fi adapter unfortunately, but if you want you can add it yourself and make a pull request.

The kernel source is here, have fun: https://github.com/ubports-santoni/android_kernel_xiaomi_santoni

**Comment by shafr** [comment]
OK, thank you.
