### ISSUE TITLE
Phone wont boot.

### ISSUE THREAD

**Issue by JoseRomanTan** [ubports-santoni/projectmanagement#28]
Getting  “Halium initrd Failed to boot” error. 
Does anyone know how to fix this?

![image](https://user-images.githubusercontent.com/71618946/96597739-c2063500-1320-11eb-8251-d88680618524.png)

I've checked if /data is formated to ext4

![image](https://user-images.githubusercontent.com/71618946/96836222-3fdc5480-1477-11eb-9b60-4696216fb17a.png)

![image](https://user-images.githubusercontent.com/71618946/96837101-78306280-1478-11eb-8e76-e08b8fa5a384.png)

**Comment by Danct12** [comment]
Since 2020/10/28, Redmi 4X has been added to UBports installer.

Please download the latest version of [UBports installer](https://github.com/ubports/ubports-installer/releases) and install it. You'll need to check "Wipe userdata" in the installer if you're from Android OS.
