### ISSUE TITLE
Ubport installer not going to recovery mode

### ISSUE THREAD

**Issue by himank3127** [ubports-santoni/projectmanagement#29]
info: Welcome to the UBports Installer version 0.7.4-beta!
warn: setting udev rules failed
warn: setting udev rules failed
info: preparing
info: checking previously downloaded firmware files
info: Downloaded file 0 of 3
info: downloading
info: downloading firmware files
info: Downloaded file 1 of 3
info: Downloaded file 2 of 3
info: Downloaded file 3 of 3
warn: lost connection to device
warn: lost connection to device
warn: lost connection to device
warn: lost connection to device
warn: lost connection to device
warn: lost connection to device
warn: lost connection to device

**Comment by saikek** [comment]
Same here with 0.8.0. After installing new bootloader / recovery, it hangs. 
It's not possible to boot into recovery anymore.

**Comment by Danct12** [comment]
I have seen the issue, however I was unable to reproduce it on my device.. so need to look into this

**Comment by tuxPM** [comment]
I succeeded booting and resuming the install, using the keycombo power: volume up and volume down at the same time.

**Comment by liss21** [comment]
Danct12, my phone (4X 2/16) does not want to enter recovery mode, apparently the installer flashes the recovery, reboots into it and nothing happens. Recovery does not load. If you try to force the phone into the recovery, then again nothing will happen. I conclude that these are either different phone revisions or the recovery image in the installer's repository is damaged. BUT, on my phone the older version that you publish on the github also refused to load. I flash for separate recovery, kernel and system. The result is exactly the same as I described above. 
Sailfish works great on it. If you want i can record video of the process.

**Comment by Danct12** [comment]
Discussion moved to here: https://github.com/ubports/ubuntu-touch/issues/1695
