### ISSUE TITLE
Adb device not showing in terminal of ubuntu 

### ISSUE THREAD

**Issue by RudraSama** [ubports-santoni/projectmanagement#30]
**Describe the bug**
Even After turning on developer mode in Ubuntu touch, we can't connect adb shell of device to Ubuntu terminal. After running command "adb devices" in terminal, it doesn't show device.

**To Reproduce**
1. Connect Device to Ubuntu 20.04
2. Turn on developer mode in device.
3. Open terminal inside desktop and run command "adb devices"
4. It shows No devices

**Device Information:**
 - Device: Redmi 4X (if you're not using this device then you're looking at wrong port
 - Rootfs: ARM64
 - Are you using Anbox?: No

**Comment by Danct12** [comment]
Please do not use this repository for bug report, please move the issue to upstream: https://github.com/ubports/ubuntu-touch/issues

**Comment by RudraSama** [comment]
okayy, sorry...
Thank you for your reply
